#this file contain the map dictionary. The structure of this dictionary is as follows:
import networkx as nx
import matplotlib.pyplot as plt
coastline = nx.DiGraph()
coastline.add_edges_from([
    ('EXTMAINENTRANCE', 'EXTPOOL'), ('EXTMAINENTRANCE', 'EXTBACKALLEY'), ('EXTMAINENTRANCE', 'EXTGARAGEROOF'), ('EXTMAINENTRANCE', 'EXTSOUTHPROMENADE'), ('EXTMAINENTRANCE', 'EXTROOFTOP'), ('EXTMAINENTRANCE', '2FHALLWAY'), ('EXTMAINENTRANCE', '1FSERVICEENTRANCE'), ('EXTMAINENTRANCE', '2FPENTHOUSE'), ('EXTMAINENTRANCE', '1FMAINLOBBY'), ('EXTMAINENTRANCE', 'EXTDJBOOTH'),
    ('EXTGARAGEROOF', 'EXTBACKALLEY'), ('EXTGARAGEROOF', 'EXTPOOL'), ('EXTGARAGEROOF', 'EXTMAINENTRANCE'),
    ('EXTBACKALLEY', 'EXTGARAGEROOF'), ('EXTBACKALLEY', 'EXTPOOL'), ('EXTBACKALLEY', 'EXTMAINENTRANCE'), ('EXTBACKALLEY', 'EXTPOOLSIDE'),
    ('EXTPOOL', 'EXTMAINENTRANCE'), ('EXTPOOL', 'EXTGARAGEROOF'), ('EXTPOOL', 'EXTBACKALLEY'), ('EXTPOOL', 'EXTDJBOOTH'), ('EXTPOOL', 'EXTCANTINA'), ('EXTPOOL', 'EXTPOOLSIDE'), ('EXTPOOL', 'EXTROOFTOP'), ('EXTPOOL', '2FHOOKAHLOUNGE'), ('EXTPOOL', '1FPOOLENTRANCE'), ('EXTPOOL', 'EXTRUINS'), ('EXTPOOL', 'EXTHOOKAHDECK'), ('EXTPOOL', 'EXTWALKWAY'),
    ('EXTPOOLSIDE', 'EXTBACKALLEY'), ('EXTPOOLSIDE', 'EXTPOOL'), ('EXTPOOLSIDE', 'EXTWALKWAY'),
    ('EXTWALKWAY', 'EXTPOOLSIDE'), ('EXTWALKWAY', 'EXTPOOL'), ('EXTWALKWAY', 'EXTRUINS'),
    ('EXTCANTINA', 'EXTPOOL'), ('EXTCANTINA', '1FKITCHEN'),
    ('EXTRUINS', 'EXTPOOL'), ('EXTRUINS', 'EXTWALKWAY'), ('EXTRUINS', '1FPOOLENTRANCE'), ('EXTRUINS', 'EXTHOOKAHDECK'), ('EXTRUINS', '1FSUNRISEBAR'), ('EXTRUINS', 'EXTROOFTOP'), ('EXTRUINS', '1FBLUEBAR'), ('EXTRUINS', '2FBILLIARDSROOM'), ('EXTRUINS', 'EXTTERRACE'), ('EXTRUINS', 'EXTSOUTHPROMENADE'), ('EXTRUINS', 'EXTBALCONY'),
    ('EXTTERRACE', 'EXTBALCONY'), ('EXTTERRACE', 'EXTRUINS'), ('EXTTERRACE', 'EXTSOUTHPROMENADE'), ('EXTTERRACE','1FOFFICE'),
    ('EXTSOUTHPROMENADE', 'EXTRUINS'), ('EXTSOUTHPROMENADE', 'EXTTERRACE'), ('EXTSOUTHPROMENADE', 'EXTROOFTOP'), ('EXTSOUTHPROMENADE', '1FSUNROOM'), ('EXTSOUTHPROMENADE', '2FSOUTHHALLYWAY'), ('EXTSOUTHPROMENADE', 'EXTMAINENTRANCE'), ('EXTSOUTHPROMENADE', 'EXTBALCONY'), ('EXTSOUTHPROMENADE', '1FSECURITYROOM'),
    ('EXTBALCONY', 'EXTTERRACE'), ('EXTBALCONY', 'EXTROOFTOP'), ('EXTBALCONY', 'EXTRUINS'), ('EXTBALCONY', 'EXTSOUTHPROMENADE'), ('EXTBALCONY', '2FAQUARIUM'),
    ('EXTHOOKAHDECK', 'EXTROOFTOP'), ('EXTHOOKAHDECK', 'EXTRUINS'), ('EXTHOOKAHDECK', 'EXTPOOL'), ('EXTHOOKAHDECK', '2FHOOKAHLOUNGE'),
    ('EXTDJBOOTH', '2FHALLOFFAME'), ('EXTDJBOOTH', 'EXTPOOL'), ('EXTDJBOOTH', 'EXTMAINENTRANCE'), ('EXTDJBOOTH', '2FVIPLOUNGE'),
    ('EXTROOFTOP', '2FBATHROOM'), ('EXTROOFTOP', 'EXTHOOKAHDECK'), ('EXTROOFTOP', 'EXTPOOL'), ('EXTROOFTOP', 'EXTSOUTHPROMENADE'), ('EXTROOFTOP', 'EXTMAINENTRANCE'), ('EXTROOFTOP', 'EXTBALCONY'), ('EXTROOFTOP', 'EXTRUINS'), ('EXTROOFTOP', '1FCOURTYARD'),
    ('1FCOURTYARD', 'EXTROOFTOP'), ('1FCOURTYARD', '1FMAINLOBBY'), ('1FCOURTYARD', '1FHALLWAY'), ('1FCOURTYARD', '2FHALLWAY'), ('1FCOURTYARD', '2FSOUTHHALLYWAY'),
    ('1FMAINLOBBY', '1FCOURTYARD'), ('1FMAINLOBBY', '1FTOILETS'), ('1FMAINLOBBY', '1FHALLWAY'), ('1FMAINLOBBY', 'EXTMAINENTRANCE'), ('1FMAINLOBBY', '1FSECURITYROOM'), ('1FMAINLOBBY', '2FHALLWAY'),
    ('1FTOILETS', '1FMAINLOBBY'), ('1FTOILETS', '1FSERVICEENTRANCE'),
    ('1FSERVICEENTRANCE', 'EXTMAINENTRANCE'), ('1FSERVICEENTRANCE', '1FTOILETS'), ('1FSERVICEENTRANCE', '1FKITCHEN'),
    ('1FKITCHEN', '1FSERVICEENTRANCE'), ('1FKITCHEN', 'EXTCANTINA'), ('1FKITCHEN', '1FHALLWAY'),
    ('1FHALLWAY', '1FKITCHEN'), ('1FHALLWAY', '1FMAINLOBBY'), ('1FHALLWAY', '1FCOURTYARD'), ('1FHALLWAY', '1FSUNRISEBAR'), ('1FHALLWAY', '1FBLUEBAR'), ('1FHALLWAY', '1FNORTHSTAIRS'),
    ('1FNORTHSTAIRS', '1FHALLWAY'), ('1FNORTHSTAIRS', '2FHALLWAY'),
    ('1FSUNRISEBAR', '1FHALLWAY'), ('1FSUNRISEBAR', '1FPOOLENTRANCE'), ('1FSUNRISEBAR', 'EXTRUINS'),
    ('1FBLUEBAR', '1FOFFICE'), ('1FBLUEBAR', '1FHALLWAY'), ('1FBLUEBAR', 'EXTRUINS'),
    ('2FHALLWAY', '1FNORTHSTAIRS'), ('2FHALLWAY', '2FHOOKAHLOUNGE'), ('2FHALLWAY', '2FBILLIARDSROOM'), ('2FHALLWAY', '1FCOURTYARD'), ('2FHALLWAY', '2FVIPLOUNGE'), ('2FHALLWAY', '2FTHEATER'), ('2FHALLWAY', '1FMAINLOBBY'), ('2FHALLWAY', '2FSOUTHHALLYWAY'),
    ('2FHOOKAHLOUNGE', 'EXTHOOKAHDECK'), ('2FHOOKAHLOUNGE', 'EXTPOOL'), ('2FHOOKAHLOUNGE', '2FHALLWAY'),
    ('2FBILLIARDSROOM', '2FHALLWAY'), ('2FBILLIARDSROOM', '2FAQUARIUM'), ('2FBILLIARDSROOM', 'EXTRUINS'),
    ('2FAQUARIUM', '2FBILLIARDSROOM'), ('2FAQUARIUM', 'EXTBALCONY'), ('2FAQUARIUM', '2FSOUTHHALLYWAY'),
    ('2FSOUTHHALLYWAY', '2FAQUARIUM'), ('2FSOUTHHALLYWAY', '2FHALLWAY'), ('2FSOUTHHALLYWAY', '1FCOURTYARD'), ('2FSOUTHHALLYWAY', 'EXTSOUTHPROMENADE'),
    ('2FVIPLOUNGE', '2FHALLWAY'), ('2FVIPLOUNGE', '2FHALLOFFAME'), ('2FVIPLOUNGE', 'EXTDJBOOTH'),
    ('2FHALLWAY', '2FVIPLOUNGE'), ('2FHALLWAY', 'EXTDJBOOTH'), ('2FHALLOFFAME', '2FPENTHOUSE'),
    ('2FPENTHOUSE', '2FBATHROOM'), ('2FPENTHOUSE', '2FHALLWAY'), ('2FPENTHOUSE', '2FTHEATER'), ('2FPENTHOUSE', 'EXTMAINENTRANCE'),
    ('2FTHEATER', '2FPENTHOUSE'), ('2FTHEATER', '2FHALLWAY'),
    ('1FSECURITYROOM', 'EXTSOUTHPROMENADE'), ('1FSECURITYROOM', '1FMAINLOBBY'), ('1FSECURITYROOM', '1FSUNROOM'),
    ('1FSUNROOM', '1FOFFICE'), ('1FSUNROOM', '1FSECURITYROOM'), ('1FSUNROOM', 'EXTSOUTHPROMENADE'),
    ('1FOFFICE', 'EXTTERRACE'), ('1FOFFICE', '1FSUNROOM'), ('1FOFFICE', '1FBLUEBAR'),
    ('1FPOOLENTRANCE', '1FSUNRISEBAR'), ('1FPOOLENTRANCE', 'EXTRUINS'), ('1FPOOLENTRANCE', 'EXTPOOL'),
    ('2FBATHROOM', '2FPENTHOUSE')
])
nx.draw(coastline, with_labels=True, node_size=100, font_size=8, node_color='lightblue')
plt.show()
