#This file contains map information.

import networkx as nx

#Initialize map graphs
coastline = nx.DiGraph()
border = nx.DiGraph()
kafedostoyevsky = nx.DiGraph()
clubhouse = nx.DiGraph()
villa = nx.DiGraph()
consulate = nx.DiGraph()
bank = nx.DiGraph()

#Define map spawns
coastline_atk_spawns = ['EXTMAINENTRANCE', 'EXTPOOL', 'EXTRUINS']
coastline_def_spawns = ['2FPENTHOUSE', '2FTHEATER', '2FBILLIARDSROOM', '2FHOOKAHLOUNGE', '1FSERVICEENTRANCE', '1FKITCHEN', '1FBLUEBAR', '1FSUNRISEBAR']
border_atk_spawns = ['EXTVALLEY']
border_def_spawns = []
kafedostoyevsky_atk_spawns = []
kafedostoyevsky_def_spawns = []
clubhouse_atk_spawns = []
clubhouse_def_spawns = []
villa_atk_spawns = []
villa_def_spawns = []
consulate_atk_spawns = []
consulate_def_spawns = []
bank_atk_spawns = []
bank_def_spawns = []
#Define dictionary to store map spawns. Index 0 is atk and index 1 is def.
map_spawns = {
    'COASTLINE':{'ATK':coastline_atk_spawns, 'DEF':coastline_def_spawns},
    'BORDER':{'ATK':border_atk_spawns, 'DEF':border_def_spawns},
    'KAFEDOSTOYEVSKY':{'ATK':kafedostoyevsky_atk_spawns, 'DEF':kafedostoyevsky_def_spawns},
    'CLUBHOUSE':{'ATK':clubhouse_atk_spawns, 'DEF':clubhouse_def_spawns},
    'VILLA':{'ATK':villa_atk_spawns, 'DEF':villa_def_spawns},
    'CONSULATE':{'ATK':consulate_atk_spawns, 'DEF':consulate_def_spawns},
    'BANK':{'ATK':bank_atk_spawns, 'DEF':bank_def_spawns}
}

#Define map_strings list
map_strings = list(map_spawns.keys())

#Add default open rooms for each map
coastline.add_edges_from([
    ('EXTMAINENTRANCE', 'EXTPOOL'), ('EXTMAINENTRANCE', 'EXTBACKALLEY'), ('EXTMAINENTRANCE', 'EXTGARAGEROOF'), ('EXTMAINENTRANCE', 'EXTSOUTHPROMENADE'), ('EXTMAINENTRANCE', 'EXTROOFTOP'), ('EXTMAINENTRANCE', '2FHALLWAY'), ('EXTMAINENTRANCE', '1FSERVICEENTRANCE'), ('EXTMAINENTRANCE', '2FPENTHOUSE'), ('EXTMAINENTRANCE', '1FMAINLOBBY'), ('EXTMAINENTRANCE', 'EXTDJBOOTH'),
    ('EXTGARAGEROOF', 'EXTBACKALLEY'), ('EXTGARAGEROOF', 'EXTPOOL'), ('EXTGARAGEROOF', 'EXTMAINENTRANCE'),
    ('EXTBACKALLEY', 'EXTGARAGEROOF'), ('EXTBACKALLEY', 'EXTPOOL'), ('EXTBACKALLEY', 'EXTMAINENTRANCE'), ('EXTBACKALLEY', 'EXTPOOLSIDE'),
    ('EXTPOOL', 'EXTMAINENTRANCE'), ('EXTPOOL', 'EXTGARAGEROOF'), ('EXTPOOL', 'EXTBACKALLEY'), ('EXTPOOL', 'EXTDJBOOTH'), ('EXTPOOL', 'EXTCANTINA'), ('EXTPOOL', 'EXTPOOLSIDE'), ('EXTPOOL', 'EXTROOFTOP'), ('EXTPOOL', '2FHOOKAHLOUNGE'), ('EXTPOOL', '1FPOOLENTRANCE'), ('EXTPOOL', 'EXTRUINS'), ('EXTPOOL', 'EXTHOOKAHDECK'), ('EXTPOOL', 'EXTWALKWAY'),
    ('EXTPOOLSIDE', 'EXTBACKALLEY'), ('EXTPOOLSIDE', 'EXTPOOL'), ('EXTPOOLSIDE', 'EXTWALKWAY'),
    ('EXTWALKWAY', 'EXTPOOLSIDE'), ('EXTWALKWAY', 'EXTPOOL'), ('EXTWALKWAY', 'EXTRUINS'),
    ('EXTCANTINA', 'EXTPOOL'), ('EXTCANTINA', '1FKITCHEN'),
    ('EXTRUINS', 'EXTPOOL'), ('EXTRUINS', 'EXTWALKWAY'), ('EXTRUINS', '1FPOOLENTRANCE'), ('EXTRUINS', 'EXTHOOKAHDECK'), ('EXTRUINS', '1FSUNRISEBAR'), ('EXTRUINS', 'EXTROOFTOP'), ('EXTRUINS', '1FBLUEBAR'), ('EXTRUINS', '2FBILLIARDSROOM'), ('EXTRUINS', 'EXTTERRACE'), ('EXTRUINS', 'EXTSOUTHPROMENADE'), ('EXTRUINS', 'EXTBALCONY'),
    ('EXTTERRACE', 'EXTBALCONY'), ('EXTTERRACE', 'EXTRUINS'), ('EXTTERRACE', 'EXTSOUTHPROMENADE'), ('EXTTERRACE','1FOFFICE'),
    ('EXTSOUTHPROMENADE', 'EXTRUINS'), ('EXTSOUTHPROMENADE', 'EXTTERRACE'), ('EXTSOUTHPROMENADE', 'EXTROOFTOP'), ('EXTSOUTHPROMENADE', '1FSUNROOM'), ('EXTSOUTHPROMENADE', '2FSOUTHHALLYWAY'), ('EXTSOUTHPROMENADE', 'EXTMAINENTRANCE'), ('EXTSOUTHPROMENADE', 'EXTBALCONY'), ('EXTSOUTHPROMENADE', '1FSECURITYROOM'),
    ('EXTBALCONY', 'EXTTERRACE'), ('EXTBALCONY', 'EXTROOFTOP'), ('EXTBALCONY', 'EXTRUINS'), ('EXTBALCONY', 'EXTSOUTHPROMENADE'), ('EXTBALCONY', '2FAQUARIUM'),
    ('EXTHOOKAHDECK', 'EXTROOFTOP'), ('EXTHOOKAHDECK', 'EXTRUINS'), ('EXTHOOKAHDECK', 'EXTPOOL'), ('EXTHOOKAHDECK', '2FHOOKAHLOUNGE'),
    ('EXTDJBOOTH', '2FHALLOFFAME'), ('EXTDJBOOTH', 'EXTPOOL'), ('EXTDJBOOTH', 'EXTMAINENTRANCE'), ('EXTDJBOOTH', '2FVIPLOUNGE'),
    ('EXTROOFTOP', 'EXTHOOKAHDECK'), ('EXTROOFTOP', 'EXTPOOL'), ('EXTROOFTOP', 'EXTSOUTHPROMENADE'), ('EXTROOFTOP', 'EXTMAINENTRANCE'), ('EXTROOFTOP', 'EXTBALCONY'), ('EXTROOFTOP', 'EXTRUINS'), ('EXTROOFTOP', '1FCOURTYARD'),
    ('1FCOURTYARD', 'EXTROOFTOP'), ('1FCOURTYARD', '1FMAINLOBBY'), ('1FCOURTYARD', '1FHALLWAY'), ('1FCOURTYARD', '2FHALLWAY'), ('1FCOURTYARD', '2FSOUTHHALLYWAY'),
    ('1FMAINLOBBY', '1FCOURTYARD'), ('1FMAINLOBBY', '1FTOILETS'), ('1FMAINLOBBY', '1FHALLWAY'), ('1FMAINLOBBY', 'EXTMAINENTRANCE'), ('1FMAINLOBBY', '1FSECURITYROOM'), ('1FMAINLOBBY', '2FHALLWAY'),
    ('1FTOILETS', '1FMAINLOBBY'), ('1FTOILETS', '1FSERVICEENTRANCE'),
    ('1FSERVICEENTRANCE', 'EXTMAINENTRANCE'), ('1FSERVICEENTRANCE', '1FTOILETS'), ('1FSERVICEENTRANCE', '1FKITCHEN'),
    ('1FKITCHEN', '1FSERVICEENTRANCE'), ('1FKITCHEN', 'EXTCANTINA'), ('1FKITCHEN', '1FHALLWAY'),
    ('1FHALLWAY', '1FKITCHEN'), ('1FHALLWAY', '1FMAINLOBBY'), ('1FHALLWAY', '1FCOURTYARD'), ('1FHALLWAY', '1FSUNRISEBAR'), ('1FHALLWAY', '1FBLUEBAR'), ('1FHALLWAY', '1FNORTHSTAIRS'),
    ('1FNORTHSTAIRS', '1FHALLWAY'), ('1FNORTHSTAIRS', '2FHALLWAY'),
    ('1FSUNRISEBAR', '1FHALLWAY'), ('1FSUNRISEBAR', '1FPOOLENTRANCE'), ('1FSUNRISEBAR', 'EXTRUINS'),
    ('1FBLUEBAR', '1FOFFICE'), ('1FBLUEBAR', '1FHALLWAY'), ('1FBLUEBAR', 'EXTRUINS'),
    ('2FHALLWAY', '1FNORTHSTAIRS'), ('2FHALLWAY', '2FHOOKAHLOUNGE'), ('2FHALLWAY', '2FBILLIARDSROOM'), ('2FHALLWAY', '1FCOURTYARD'), ('2FHALLWAY', '2FVIPLOUNGE'), ('2FHALLWAY', '2FTHEATER'), ('2FHALLWAY', '1FMAINLOBBY'), ('2FHALLWAY', '2FSOUTHHALLYWAY'), ('2FHALLWAY', 'EXTMAINENTRANCE'),
    ('2FHOOKAHLOUNGE', 'EXTHOOKAHDECK'), ('2FHOOKAHLOUNGE', 'EXTPOOL'), ('2FHOOKAHLOUNGE', '2FHALLWAY'),
    ('2FBILLIARDSROOM', '2FHALLWAY'), ('2FBILLIARDSROOM', '2FAQUARIUM'), ('2FBILLIARDSROOM', 'EXTRUINS'),
    ('2FAQUARIUM', '2FBILLIARDSROOM'), ('2FAQUARIUM', 'EXTBALCONY'), ('2FAQUARIUM', '2FSOUTHHALLYWAY'),
    ('2FSOUTHHALLYWAY', '2FAQUARIUM'), ('2FSOUTHHALLYWAY', '2FHALLWAY'), ('2FSOUTHHALLYWAY', '1FCOURTYARD'), ('2FSOUTHHALLYWAY', 'EXTSOUTHPROMENADE'),
    ('2FVIPLOUNGE', '2FHALLWAY'), ('2FVIPLOUNGE', '2FHALLOFFAME'), ('2FVIPLOUNGE', 'EXTDJBOOTH'),
    ('2FHALLOFFAME', '2FVIPLOUNGE'), ('2FHALLOFFAME', '2FPENTHOUSE'), ('2FHALLOFFAME', 'EXTDJBOOTH'),
    ('2FPENTHOUSE', '2FBATHROOM'), ('2FPENTHOUSE', '2FHALLOFFAME'), ('2FPENTHOUSE', '2FTHEATER'), ('2FPENTHOUSE', 'EXTMAINENTRANCE'),
    ('2FTHEATER', '2FPENTHOUSE'), ('2FTHEATER', '2FHALLWAY'),
    ('1FSECURITYROOM', 'EXTSOUTHPROMENADE'), ('1FSECURITYROOM', '1FMAINLOBBY'), ('1FSECURITYROOM', '1FSUNROOM'),
    ('1FSUNROOM', '1FOFFICE'), ('1FSUNROOM', '1FSECURITYROOM'), ('1FSUNROOM', 'EXTSOUTHPROMENADE'),
    ('1FOFFICE', 'EXTTERRACE'), ('1FOFFICE', '1FSUNROOM'), ('1FOFFICE', '1FBLUEBAR'),
    ('1FPOOLENTRANCE', '1FSUNRISEBAR'), ('1FPOOLENTRANCE', 'EXTRUINS'), ('1FPOOLENTRANCE', 'EXTPOOL'),
    ('2FBATHROOM', '2FPENTHOUSE')
], edge_visited = 0)

border.add_edges_from([
    ('EXTVALLEY', 'EXTPARKINGLOTENT'), ('EXTVALLEY', 'EXTPEDESTRIANCUSTOMS'), ('EXTVALLEY', 'EXTWATCHTOWER'),
    ('EXTWATCHTOWER', 'EXTVALLEY'), ('EXTWATCHTOWER', 'EXTPEDESTRIANCUSTOMS'),
    ('EXTPEDESTRIANCUSTOMS', 'EXTVALLEY'), ('EXTPEDESTRIANCUSTOMS', 'EXTWATCHTOWER'), ('EXTPEDESTRIANCUSTOMS', 'EXTSOUTHBALCONY'), ('EXTPEDESTRIANCUSTOMS', 'EXTPARKINGLOTENT'), ('EXTPEDESTRIANCUSTOMS', 'EXTROOF'), ('EXTPEDESTRIANCUSTOMS', 'EXTEASTALLEY'), ('EXTPEDESTRIANCUSTOMS', 'EXTPEDESTRIANENTRANCE'), ('EXTPEDESTRIANCUSTOMS', '1FPASSPORTCHECK'),
    ('EXTPARKINGLOTENT', 'EXTPEDESTRIANCUSTOMS'), ('EXTPARKINGLOTENT', 'EXTVALLEY'), ('EXTPARKINGLOTENT', 'EXTPEDESTRIANEXIT'), ('EXTPARKINGLOTENT', 'EXTPARKINGLOT'), ('EXTPARKINGLOTENT', 'EXTPARKINGLOTALLEY'), ('EXTPARKINGLOTENT', 'EXTWESTBALCONY'),
    ('EXTPEDESTRIANEXIT', 'EXTPARKINGLOTENT'), ('EXTPEDESTRIANEXIT', 'EXTWESTTOWER'), ('EXTPEDESTRIANEXIT', 'EXTWESTVEHEXIT'),
    ('EXTWESTVEHEXIT', 'EXTPEDESTRIANEXIT'), ('EXTWESTVEHEXIT', 'EXTWESTTOWER'), ('EXTWESTVEHEXIT', 'EXTWESTROAD'),
    ('EXTWESTTOWER', 'EXTPEDESTRIANEXIT'), ('EXTWESTTOWER', 'EXTWESTVEHEXIT'), ('EXTWESTTOWER', 'EXTWESTROAD'), ('EXTWESTTOWER', 'EXTPARKINGLOT'),
    ('EXTWESTROAD', 'EXTWESTVEHEXIT'), ('EXTWESTROAD', 'EXTWESTTOWER'), ('EXTWESTROAD', 'EXTPARKINGLOT'), ('EXTWESTROAD', 'EXTVEHICLECUSTOMS'), ('EXTWESTROAD', 'EXTPARKINGLOTALLEY'),
    ('EXTPARKINGLOT', 'EXTWESTROAD'), ('EXTPARKINGLOT', 'EXTWESTTOWER'), ('EXTPARKINGLOT', 'EXTPARKINGLOTALLEY'), ('EXTPARKINGLOT', 'EXTPARKINGLOTENT'),
    ('EXTPARKINGLOTALLEY', 'EXTPARKINGLOT'), ('EXTPARKINGLOTALLEY', 'EXTPARKINGLOTENT'), ('EXTPARKINGLOTALLEY', 'EXTWESTROAD'), ('EXTPARKINGLOTALLEY', 'EXTVEHICLECUSTOMS'), ('EXTPARKINGLOTALLEY', 'EXTROOF'), ('EXTPARKINGLOTALLEY', 'EXTWESTBALCONY'), ('EXTPARKINGLOTALLEY', '1FEXITHALLWAY'), ('EXTPARKINGLOTALLEY', '1FSUPPLYROOM'),
    ('EXTVEHICLECUSTOMS', 'EXTROOF'), ('EXTVEHICLECUSTOMS', 'EXTPARKINGLOT'), ('EXTVEHICLECUSTOMS', 'EXTWESTROAD'), ('EXTVEHICLECUSTOMS', '1FVENTILATIONROOM'), ('EXTVEHICLECUSTOMS', '2FARMORYLOCKERS'), ('EXTVEHICLECUSTOMS', '2FARCHIVES'), ('EXTVEHICLECUSTOMS', 'EXTCRASHSCENE'),
    ('EXTCRASHSCENE', 'EXTVEHICLECUSTOMS'), ('EXTCRASHSCENE', 'EXTROOF'), ('EXTCRASHSCENE', 'EXTNORTHBALCONY'), ('EXTCRASHSCENE', 'EXTEASTALLEY'), ('EXTCRASHSCENE', 'EXTEASTBALCONY'), ('EXTCRASHSCENE', 'EXTEASTROAD'),
    ('EXTEASTROAD', 'EXTEASTVEHENT'), ('EXTEASTROAD', 'EXTCRASHSCENE'), ('EXTEASTROAD', 'EXTEASTALLEY'),
    ('EXTEASTVEHENT', 'EXTEASTROAD'), ('EXTEASTVEHENT', 'EXTPEDESTRIANENTRANCE'),
    ('EXTEASTALLEY', '1FTELLERS'), ('EXTEASTALLEY', 'EXTROOF'), ('EXTEASTALLEY', 'EXTCRASHSCENE'), ('EXTEASTALLEY', 'EXTEASTROAD'), ('EXTEASTALLEY', 'EXTPEDESTRIANENTRANCE'), ('EXTEASTALLEY', 'EXTPEDESTRIANCUSTOMS'),
    ('EXTPEDESTRIANENTRANCE', 'EXTEASTALLEY'), ('EXTPEDESTRIANENTRANCE', 'EXTPEDESTRIANCUSTOMS'), ('EXTPEDESTRIANENTRANCE', 'EXTEASTVEHENT'),
    ('EXTSOUTHBALCONY', 'EXTPEDESTRIANCUSTOMS'), ('EXTSOUTHBALCONY', 'EXTWESTBALCONY'), ('EXTSOUTHBALCONY', '2FBREAKROOM'), ('EXTSOUTHBALCONY', '1FWAITINGROOM'), ('EXTSOUTHBALCONY', '2FEASTSTAIRS'),
    ('EXTWESTBALCONY', 'EXTSOUTHBALCONY'), ('EXTWESTBALCONY', 'EXTPARKINGLOTENT'), ('EXTWESTBALCONY', 'EXTPARKINGLOTALLEY'), ('EXTWESTBALCONY', '2FSECURITYROOM'), ('EXTWESTBALCONY', '2FARMORYLOCKERS'),
    ('EXTROOF', '')
], edge_visited = 0)
## TODO: Finish mapping Border.

#Add default closed rooms for each map
coastline.add_edges_from([
    ('1FBLUEBAR', '1FSUNRISEBAR'), ('1FBLUEBAR', '1FCOURTYARD'),
    ('1FSUNRISEBAR', '1FBLUEBAR'), ('1FSUNRISEBAR', '2FHOOKAHLOUNGE'),
    ('1FCOURTYARD', '1FBLUEBAR'), ('1FCOURTYARD', '2FBILLIARDSROOM'),
    ('1FMAINLOBBY', '1FSERVICEENTRANCE'), ('1FMAINLOBBY', '2FPENTHOUSE'),
    ('1FSERVICEENTRANCE', '1FMAINLOBBY'),
    ('2FHOOKAHLOUNGE', '2FBILLIARDSROOM'), ('2FHOOKAHLOUNGE', '1FSUNRISEBAR'),
    ('2FBILLIARDSROOM', '2FHOOKAHLOUNGE'), ('2FBILLIARDSROOM', '1FCOURTYARD'),
    ('2FVIPLOUNGE', '2FPENTHOUSE'),
    ('2FPENTHOUSE', '2FVIPLOUNGE'), ('2FPENTHOUSE', '1FMAINLOBBY'),
    ('2FBATHROOM', '2FHALLOFFAME'), ('2FBATHROOM', 'EXTROOFTOP'),
    ('2FHALLOFFAME', '2FBATHROOM'),
    ('EXTROOFTOP', '2FBATHROOM'),
    ('2FSOUTHHALLYWAY', '1FSECURITYROOM'),
    ('1FSECURITYROOM', '2FSOUTHHALLYWAY'),
    ('1FOFFICE', '2FAQUARIUM'),
    ('2FAQUARIUM', '1FOFFICE')
], open = False, edge_visited = 0)

#Set node attributes for each map.
nx.set_node_attributes(coastline, 0, 'node_visited')
nx.set_node_attributes(border, 0, 'node_visited')
nx.set_node_attributes(kafedostoyevsky, 0, 'node_visited')
nx.set_node_attributes(clubhouse, 0, 'node_visited')
nx.set_node_attributes(villa, 0, 'node_visited')
nx.set_node_attributes(consulate, 0, 'node_visited')
nx.set_node_attributes(bank, 0, 'node_visited')

## TODO: DATA: Add node attributes for death.
## TODO: DATA: Add edge attributes for death.
